require 'dotenv'
Dotenv.load

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1399980480022162
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>